const doctorsList = [
  {
    id: "1",
    name: "Aleks",
    surname: "Dyatloff",
    specialityId: "6",
    isPediatrician: true,
    cityId: "3",
  },
  {
    id: "2",
    name: "Asya",
    surname: "Plachkova",
    specialityId: "5",
    isPediatrician: true,
    cityId: "3",
  },
  {
    id: "3",
    name: "Vladislav",
    surname: "Strizinec",
    specialityId: "3",
    isPediatrician: true,
    cityId: "3",
  },
  {
    id: "4",
    name: "Elisaveta",
    surname: "Goroh",
    specialityId: "2",
    isPediatrician: false,
    cityId: "1",
  },
  {
    id: "5",
    name: "Aleksander",
    surname: "Romashkov",
    specialityId: "13",
    isPediatrician: true,
    cityId: "2",
  },
  {
    id: "6",
    name: "Dmitry",
    surname: "Kuzmin",
    specialityId: "7",
    isPediatrician: false,
    cityId: "3",
  },
  {
    id: "7",
    name: "Anastasia",
    surname: "Zinchenko",
    specialityId: "11",
    isPediatrician: true,
    cityId: "6",
  },
  {
    id: "8",
    name: "Zoe",
    surname: "Saldana",
    specialityId: "5",
    isPediatrician: false,
    cityId: "7",
  },
  {
    id: "9",
    name: "Jake",
    surname: "Mitt",
    specialityId: "4",
    isPediatrician: false,
    cityId: "12",
  },
  {
    id: "10",
    name: "Jack",
    surname: "Sparrow",
    specialityId: "10",
    isPediatrician: true,
    cityId: "10",
  },
  {
    id: "11",
    name: "Inna",
    surname: "Bread",
    specialityId: "12",
    isPediatrician: false,
    cityId: "13",
  },
  {
    id: "12",
    name: "John",
    surname: "Whikk",
    specialityId: "3",
    isPediatrician: false,
    cityId: "14",
  },
  {
    id: "13",
    name: "Andrei",
    surname: "Hovalski",
    specialityId: "8",
    isPediatrician: true,
    cityId: "9",
  },
  {
    id: "14",
    name: "Maksim",
    surname: "Karashenko",
    specialityId: "7",
    isPediatrician: false,
    cityId: "4",
  },
  {
    id: "15",
    name: "Anton",
    surname: "Polyakov",
    specialityId: "2",
    isPediatrician: true,
    cityId: "5",
  },
  {
    id: "16",
    name: "Vitya",
    surname: "Izvesnyakov",
    specialityId: "5",
    isPediatrician: false,
    cityId: "8",
  },
]

export default doctorsList
